name = "MPBUtils"
uuid = "a5feb4ea-5495-4677-96f8-dddb76c9eb4c"
authors = ["Thomas Christensen <tchr@mit.edu> and contributors"]
version = "0.1.10"

[deps]
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymmetryBases = "cb68ded9-7e8c-45d3-bc66-19b5867c0467"

[compat]
Crystalline = "0.4.16"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
